2017-02-25 13:23:49,650	INFO	main	<module>	Line:13	app started
2017-02-25 13:23:49,669	INFO	_internal	_log	Line:87	 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2017-02-25 13:23:53,582	ERROR	accountDAO	getaccountbydatelength	Line:131	(mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type [SQL: u'SELECT account.account_id AS account_account_id, account.account_item AS account_account_item, account.account_money AS account_account_money, account.account_type AS account_account_type, account.account_date AS account_account_date, account.account_addition AS account_account_addition \nFROM account \nWHERE account.account_user = %(account_user_1)s AND account.account_date = %(account_date_1)s ORDER BY account.account_date DESC'] [parameters: {u'account_user_1': 1, u'account_date_1': (u'2017-02-28',)}]
2017-02-25 13:23:53,585	INFO	_internal	_log	Line:87	192.168.99.1 - - [25/Feb/2017 13:23:53] "GET /account/1/77a0891f1f8e339d80c07507c23fdf90 HTTP/1.1" 200 -
